# Generated by Django 6.1.1 on 2026-09-20 02:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_cuenta', models.CharField(default='Activo', max_length=20)),
                ('es_socio', models.BooleanField(default=False)),
                ('es_entrenador', models.BooleanField(default=False)),
                ('es_recepcionista', models.BooleanField(default=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('equipo_requerido', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=100, null=True)),
                ('zona_ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('url_video_tecnica', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ejercicio',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id_plan_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100)),
                ('moneda_origen', models.CharField(default='BOB', max_length=10)),
                ('costo_base_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('acceso_piscina', models.BooleanField(default=False)),
                ('clases_grupales', models.BooleanField(default=False)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'plan_membresia',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('moneda_facturacion', models.CharField(default='BOB', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rutina', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('calorias_estimadas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('duracion_estimada_mins', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'rutina',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.OneToOneField(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_entrenador', models.OneToOneField(db_column='id_entrenador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia_profesional', models.TextField(blank=True, null=True)),
                ('anios_experiencia', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('red_social_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'entrenador',
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id_recepcionista', models.OneToOneField(db_column='id_recepcionista', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recepcionista',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.OneToOneField(db_column='id_socio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_inicial_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('contacto_emerg_nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'socio',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_usuario_db', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('id_subcategoria', models.ForeignKey(blank=True, db_column='id_subcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriaproducto')),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id_contrato_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrato_laboral',
            },
        ),
        migrations.CreateModel(
            name='MarcacionPersonal',
            fields=[
                ('id_marcacion_personal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(max_length=20)),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_contrato_laboral', models.ForeignKey(db_column='id_contrato_laboral', on_delete=django.db.models.deletion.CASCADE, to='api.contratolaboral')),
            ],
            options={
                'db_table': 'marcacion_personal',
            },
        ),
        migrations.CreateModel(
            name='PagoPlanilla',
            fields=[
                ('id_pago_planilla', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('periodo_anio', models.IntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pagada', models.DateField()),
                ('id_contrato_laboral', models.ForeignKey(db_column='id_contrato_laboral', on_delete=django.db.models.deletion.RESTRICT, to='api.contratolaboral')),
            ],
            options={
                'db_table': 'pago_planilla',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('moneda_origen', models.CharField(default='BOB', max_length=10)),
                ('precio_base_original', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_promedio_local', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('clasificacion_abc', models.CharField(blank=True, max_length=2, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='api.categoriaproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='KardexInventario',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
            ],
            options={
                'db_table': 'kardex_inventario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('monto_total_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_venta', models.CharField(default='Completada', max_length=20)),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.RESTRICT, to='api.metodopago')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.RESTRICT, to='api.socio')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nro_factura_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('monto_total_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_total_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_compra', models.CharField(default='Completada', max_length=20)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.RESTRICT, to='api.proveedor')),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.RESTRICT, to='api.administrador')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.RESTRICT, to='api.administrador')),
            ],
            options={
                'db_table': 'arqueo_caja',
            },
        ),
        migrations.CreateModel(
            name='AlertaReposicion',
            fields=[
                ('id_alerta_repo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_evento_global', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_urgencia', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_sugerida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_alerta', models.CharField(default='Pendiente', max_length=20)),
                ('orden_compra_erp', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.RESTRICT, to='api.administrador')),
            ],
            options={
                'db_table': 'alerta_reposicion',
            },
        ),
        migrations.CreateModel(
            name='MarcacionAcceso',
            fields=[
                ('id_marcacion_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.CASCADE, to='api.socio')),
            ],
            options={
                'db_table': 'marcacion_acceso',
            },
        ),
        migrations.CreateModel(
            name='ContratoMembresia',
            fields=[
                ('id_contrato_mem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('monto_pagado_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_membresia', models.CharField(default='Activa', max_length=20)),
                ('id_renovacion', models.ForeignKey(blank=True, db_column='id_renovacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contratomembresia')),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.RESTRICT, to='api.metodopago')),
                ('id_plan_mem', models.ForeignKey(db_column='id_plan_mem', on_delete=django.db.models.deletion.RESTRICT, to='api.planmembresia')),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.RESTRICT, to='api.socio')),
            ],
            options={
                'db_table': 'contrato_membresia',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id_asignacion_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_rutina', models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.RESTRICT, to='api.rutina')),
                ('id_entrenador', models.ForeignKey(db_column='id_entrenador', on_delete=django.db.models.deletion.RESTRICT, to='api.entrenador')),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.CASCADE, to='api.socio')),
            ],
            options={
                'db_table': 'asignacion_rutina',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_unitario_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unitario_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
            ],
            options={
                'db_table': 'detalle_compra',
                'unique_together': {('id_compra', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticiones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descanso_minutos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_ejercicio', models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('id_rutina', models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
            ],
            options={
                'db_table': 'detalle_rutina',
                'unique_together': {('id_rutina', 'id_ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=15)),
                ('tolerancia_minutos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_contrato_laboral', models.ForeignKey(db_column='id_contrato_laboral', on_delete=django.db.models.deletion.CASCADE, to='api.contratolaboral')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'db_table': 'horario_laboral',
                'unique_together': {('id_turno', 'id_contrato_laboral', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_plan_membresia', models.ForeignKey(db_column='id_plan_membresia', on_delete=django.db.models.deletion.RESTRICT, to='api.planmembresia')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
            options={
                'db_table': 'detalle_venta_servicio',
                'unique_together': {('id_venta', 'id_plan_membresia')},
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_origen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_local', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
            options={
                'db_table': 'detalle_venta_producto',
                'unique_together': {('id_venta', 'id_producto')},
            },
        ),
    ]
